### ISSUE TITLE
Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues'

### ISSUE THREAD

**Issue by JonasJasas** [RedBearSys/RedBear.LogDNA.Extensions.Logging.Web#3]
Adding this code to hello world core mvc project:
```csh
public void ConfigureServices(IServiceCollection services)
{
    var options = new LogDNAOptions("xxxxxxxxxxxxxxxxxxxxxx", LogLevel.Debug).AddWebItems();
    services.AddLogging(loggingBuilder => loggingBuilder.AddLogDNA(options));

    services.AddRazorPages();
}
```

Getting an error:

```
Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
 ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at RedBear.LogDNA.Extensions.Logging.LogDNALogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

**Comment by siderisltd** [comment]
I have the same problem 
TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by siderisltd** [comment]
@JonasJasas it looks like this library was built for netcore 2.0. In 3.0 the type FormattedLogValues is made internal and can't be accessed. I was able to make it work by extending the library and I can see my logs into the logsDNA. I might be able to make a PR here for this library these days :)

**Comment by siderisltd** [comment]
@JonasJasas -> https://github.com/RedBearSys/RedBear.LogDNA.Extensions.Logging/pull/5
